### ISSUE TITLE
Suggestion: Resize Tails model smaller + a bit more things.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#125]
**Describe your suggestion**

Models & animations updating

Resize tails model smaller similar too Isabelle, Hatkid or Niko from oneshot.
Its gigantic proportions makes it quite large compared too the rest of even the normal models besides the Pikachu model.
Mentioned this particular thing once too Light but figured I'd put it in here as well.

Perhaps change the model entirely & find the classic tails model from sonic generations & get that working in TF2, perhaps reach out too someone that ported over a gmod model of it & ask if you could use that as a base for this.

Another thing is perhaps update some of the models so they do the new taunt animations rather then just do the standard idle standing animation or t-pose/a-pose while the character slides forward or does whatever in said instance that isn't the taunt animation itself.

Like the astronaut model from moonbase alpha, phoenix wright not having the taunt animations for The victory lap, scorching skater, boxtrot for example, there are a few more as well i could write down if needed.

SZF: mostly weapons.
Warrior's spirit: Seems too take out players rather quickly regardless of minicrits or not with the combo of throwing a sandvich or if said player is taking minicrits from jarate/ exploded boomer.

killing gloves of boxing: not sure if it does similar damage too the warriors spirit

Holiday punch: Someone mentioned yesterday you can stun players with this as a zombie i think, worth checking out if true or if they meant you can do that with the standard showdown taunt like you can with the regular fists.

Sandvich: People tend too throw these and with several heavies in a row doing it eats your hp ridiculously fast especially in front of any spawndoor & mid fight getting surrounded by said heavies.

Perhaps have it drain a lower amount of hp and reset slower for said heavies.
 id say 20% off from what it is currently draining or make said hp regen over time just too make anyone vulnerable in the moment but not impossible too survive having 3x heavies throw the sandvich and then bash you too bits while a engineer or pyro.

Or if possible give it a slight aoe effect like getting hit by the sandman ball does in a smaller area of effect then the sandman but perhaps 2 hp per 150 ms.
(Just so said heavies don't just throw down 7 sandviches that drains 5 - 8 hp each per second.)
Ofc block it from being possible too have the aoe effect go through the spawndoors will be needed then.

Tank: Perhaps adjust the max hp calculation a bit per player alive on red.
tank does quite a bit of damage per hit but with many alive its possible too take down.
Bit annoying too fight though when chaos happens with the tank being barely larger & just green, maybe add in the vsh arrow for the tank too make it stand out a bit more would let players be able too focus said tank.

**Describe alternatives you've considered**

**Additional context**

While not a rush too get this going i figured id just get it written down on the github too make it easier too keep track.

**Comment by shinsasch** [comment]
> Warrior's spirit: Seems too take out players rather quickly regardless of minicrits or not with the combo of throwing a sandvich or if said player is taking minicrits from jarate/ exploded boomer.

It deals more damage in exchange that you take more damage as well. Sandvich throw into melee is an 'intermediate' mechanic which is a valid way to play the Heavy. The Boomer's Jarate lasts for a short moment which scales based on the distance from the Boomer, if you are not close to the Boomer you will not be punished as much as if you were almost next to it.

This is a matter of awareness and being able to know what things do in the gamemode. The Warrior's Spirit damage output, Sandvich damage output and Boomer's Jarate duration will not be adjusted. However, the movement speed penalty on the Warrior's Spirit and Holiday Punch may be increased, or different changes may be made that indirectly impact these weapons, the class or anything else _but_ doing a simple damage 'buff' or 'debuff'. 


> killing gloves of boxing: not sure if it does similar damage too the warriors spirit

Making one kill with the Killing Gloves of Boxing replaces the 5 second crits with perma mini-crits until you die. It has no changes otherwise from it's regular version.


> Holiday punch: Someone mentioned yesterday you can stun players with this as a zombie i think, worth checking out if true or if they meant you can do that with the standard showdown taunt like you can with the regular fists.

Yes, you can stun players with the Holiday Punch for 1 second and deals 10 damage to the victim while disabling any form of weapon usage on the attacker for 1.25 seconds to prevent stun-locking on your own. So nothing worth to check out here, keep in mind that any weapon you use is as much as it's regular version as possible with exceptions highlighted in the chat when you spawn.


> Sandvich: People tend too throw these and with several heavies in a row doing it eats your hp ridiculously fast especially in front of any spawndoor & mid fight getting surrounded by said heavies.

For Sandviches camping spawndoors: don't walk over the Sandviches, the damage output of these was lowered too and it has been in a fine spot since then.


> Perhaps have it drain a lower amount of hp and reset slower for said heavies.
id say 20% off from what it is currently draining or make said hp regen over time just too make anyone vulnerable in the moment but not impossible too survive having 3x heavies throw the sandvich and then bash you too bits while a engineer or pyro. (...suggestions to change the Sandvich)

No further adjustments will be made to the Sandvich's damage output. If you are outnumbered, you are outnumbered, decreasing [a thing]'s damage with [an amount] will not change the outcome. Furthermore, introducing a "different" version from the Scout's sole specialty is pointless and will not improve or fix anything to the gamemode. The Sandvich is intended for single target damage from outside melee range or to lay traps, rewarding good usage. In the future there may be a change done to the Sandvich in which it will have it's maximum damage adjusted in exchange to slow down the target or 'disable' the target for a small duration to make it work like an actual trap.


> Tank: Perhaps adjust the max hp calculation a bit per player alive on red. tank does quite a bit of damage per hit but with many alive its possible too take down.

The Tank is planned to get further adjustments to it's health pool, but rather that it loses less health over time but will scale with less health as more Survivors are in play to allow Survivors to combat the Tank better but at the same time giving the Tank access to more 'time' to engage the Survivors, as the Tank tends to be already at half health before they reach the Survivors in certain situations on certain, large maps.


> Bit annoying too fight though when chaos happens with the tank being barely larger & just green, maybe add in the vsh arrow for the tank too make it stand out a bit more would let players be able too focus said tank.

The Tank has a glowing line around it's model, as does the Kingpin. That is already enough to see where the Tank is at in the crowd and does a better job than an arrow.


I appreciate the thoughts and suggested changes for the gamemode, I hope that any upcoming changes will satisfy your questions / concerns (in)directly, since there are quite a few things that can be adjusted, but it is a process of a lot of evaluation and experience over the past year(s) of having developed and worked on Player versus Player gamemodes where balance is top priority. So thank you and please look forward to any future changes to Super Zombie Fortress!

**Comment by ThatAverageJoe** [comment]
> Resize tails model smaller similar too Isabelle, Hatkid or Niko from oneshot.
> Perhaps change the model entirely & find the classic tails model from sonic generations & get that >working in TF2, perhaps reach out too someone that ported over a gmod model of it & ask if you >could use that as a base for this.

Although it's currently not exactly high on my priority list, I will consider this.

> Another thing is perhaps update some of the models so they do the new taunt animations rather then >just do the standard idle standing animation or t-pose/a-pose while the character slides forward or >does whatever in said instance that isn't the taunt animation itself.

I will look into this, although it should be noted that some of the models don't play the animations as they are rigged to different skeletons (For example, Monokuma's model is rigged for Heavy but can be equipped by any class, which means that some animations won't play when you attempt to do a class-specific taunt).

**Comment by Light08** [comment]
> I will look into this, although it should be noted that some of the models don't play the animations as they are rigged to different skeletons (For example, Monokuma's model is rigged for Heavy but can be equipped by any class, which means that some animations won't play when you attempt to do a class-specific taunt, so in that situation, it unfortunately cannot be helped).

To my knowledge some older models are lacking certain newer taunt animations, resulting in them missing completly. I'm no expert nor completly sure if these models require a recompile but I remember seeing something config related to it? It might have been related to workshop taunts, and I think these are somehow configurable to be usable by any class, as I remember one of our older models was able to use taunts from different classes properly.
