### ISSUE TITLE
Map Bug: szf_toyfortress_v18 random respawns

### ISSUE THREAD

**Issue by V1NAlt** [DFS-Servers/BugReportsAndSuggestions#129]
**Describe the bug**
In this map, people that have been turned into zombies or spawned as them randomly respawn while alive. This occurs for EVERY type of infected, making a victory for BLU harder.

**To Reproduce**
For an *example*:
1. Go onto szf_toyfortress_v18
2. Be a BLU/Infected
3. Try to attack a RED or wander
4. Sudden respawn.

**Expected behavior**
No type of forced respawn should happen unless dead.

**Screenshots or error logs**
Will try to provide a video if needed, but so far, no luck at getting the bug to even execute again.

**Server Info (please complete the following information):**
 - Region: EU
 - IP 89.35.29.11:27145

**Additional context**
I might be a bit wrong about the respawns if the checkpoints are just close to each other for the infected.

**Comment by shinsasch** [comment]
The respawn comes from a new system that acts relatively quickly when a player is considered "stuck" by taking their vectors, which only works in that way because of the player being resized in certain cases, especially on crouch where it resizes you back to your normal size to make you able to traverse all parts of certain maps. Now this fix apparently triggers almost anywhere on toy fortress for some reason even though the entity brushes people collide with are disabled and shouldn't be considered in the logic at all.

This was already addresaed last night but probably not uploaded, but now it also checks if you actually move or not. If it is still broken i'll check it out later this week, as I am in the process of doing a big rewrite for the plugin.

**Comment by shinsasch** [comment]
fix should be live, if it is still present feel free to comment on here.

**Comment by shinsasch** [comment]
anti-stuck system needs a rework so re-opening

**Comment by shinsasch** [comment]
until further inspection, the anti-stuck mechanic was actually completely pointless. so this is now addressed for after this maintenance.

**Comment by Dispenz0r** [comment]
Thanks for the bug report and bug fix, the patch should be applied in an upcoming small hotfix patch really soon.

**Comment by Dispenz0r** [comment]
Patch should be applied now
