### ISSUE TITLE
Allow users too change the prices of their active auctions until due date.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#177]
**Describe your suggestion**

Just too make it a bit easier too move items that might not sell for ridiculously high prices or that has almost 0 interest no matter what price it is & so people can actually make sensible auction prices rather then just a joke listing selling their dj grooves for 10 million credits that obviously no one has access to put down while offers sits at like 100 credits because no one is actually bidding on it.

**Describe alternatives you've considered**
Or as an alternative just have a button too remove listing of said auction directly so people can put them up again with a new lower price or higher price if it gained interest but didn't reach close too what they were hoping for.

**Additional context**
Alphabetic sorting of all /pack menu's in the works or not something considered yet ?

Tends too be a bit difficult sorting through modules when you got more then 50 of them or perhaps sort them in a way that puts the same modules as x3 instead like satans blue footprints 3x instead of having them spread out over 7 pages of your modules too put on auction.

**Comment by Light08** [comment]
Except that's how it's supposed to work. If you wanna get your stuff sold, you should put responsible prices in there, otherwise your item will sit there for 2 weeks and just return. The system works as it should and there's no reason to change it at all. If I were to put a remove sytem then I'd likely recompensate it with a 5% fee of the offer / buyout price, something nobody would like to see I assume.

Items are sorted after their date of addition to the Auction House. There are plans of changing the offer-system but other than that there won't be any other changes.
