### ISSUE TITLE
Escape Tickets, But They Don't Actually Let You Escape

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#183]
**Describe the Bug:**
The "Escape Tickets" special round in Slender Fortress doesn't allow you to pick up a page, thus making it impossible to win.

**To Reproduce:**
1. Be on a Slender map
2. Let RNG put you on RED
3. The special round should choose "Escape Tickets"
4. Find a page

**Expected Behaviour:**
You should exit the map immediately upon collecting a page.

**Server Info:**
 - Region: [EU]
 - IP: 89.35.29.11:27145

**Additional Context:**
This happened on slender_manor, so I'm not sure if this is the only map that's bugged.

**Comment by Glubbable** [comment]
Escape Tickets was changed in my build to require a user to pick up the page and then head to the exit in the map in order to escape. However this isn't exactly possible in maps with a closed escape.

Dispenz0r is also going to need to set sf2_unreachable_escape to 1 on all the maps that have an unreachable escape due to the changed behavior in this special.

So currently as it is, once a player picks up a page or has picked up a page, they can head to the escape and leave the map.

**Comment by Creataurus** [comment]
I can see three examples for these kinds of maps admittedly, sl_containmentbreach, sl_frightyard, and sl_decay. I know there's that one with the elevator you have to wait 4 minutes 30 seconds or something like that, but this is honestly an interesting change. I sort of discovered this new feature on sl_frostrun just by thinking about why I didn't teleport when picking up an escape ticket so good on you Glub for this new feature.

**Comment by Glubbable** [comment]
Forgot to mention that Escape Tickets cannot be picked on RAID, Survival, Proxy Survival or Adventure maps. This is because these are modes that naturally do not have open escapes. The Page Count on the map also has be 4 or more for regular maps.

**Comment by Dispenz0r** [comment]
I've changed the cvar Glubs mentioned above on the said maps so this should hopefully be fixed now, thanks!
