### ISSUE TITLE
Slender Special Round Suggestion

### ISSUE THREAD

**Issue by Creataurus** [DFS-Servers/BugReportsAndSuggestions#189]
I was looking at both the slender pages on the forum and the DFS sound files when I just thought of a special round for slender, particularly revolving around Micheal Jackson.

Maybe a special round where Micheal Jackson spawns in as a standalone boss to assist with stalker bosses, thought of the round name being "Smooth Criminal" with a description of, "You've been helped by, you've been saved by a smooth criminal." Granted, MJ won't have any music to signal that he's nearby of course.

There aren't really any alternatives to this special round, but if future helper bosses do get added, I'm wondering if it's possible to add a general special round to replace Smooth Criminal, with it just being called, "Assistance" with a description of, "Someone has come to aid you."

I know that this could potentially be a pain to code in due to the need of having to make a special round both revolving around one type of boss, stalkers, and it having to only be MJ that joins in and not Bubbles. If you do decide to add this, I wish you the best of luck, and thank you.

**Comment by Light08** [comment]
We do not develope Slender Fortress.

If you want to make suggestions towards the plugin itself (not configs, but which seems to be the case here), you should redirect it towards the group or (current) maker of the gamemode. However, since this is a suggestion in direct relation with one of our own bosses, chances are this isn't going to happen, ever.
