### ISSUE TITLE
Inventory Stacking

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#203]
**Is your feature request related to a problem?:**
Community items and boss keys can get quite cluttered up in your inventory and makes it difficult to find the thing you want.

**Describe your suggestion:**
Community items and boss keys should be put into their own separate categories so they're easier to find while less space is used up. As an example, every Community item would be put in a "Community" folder, same with boss keys being put in a "Boss" one. As a bonus, they could be at the very top of your inventory.

**Describe alternatives you've considered:**
Uh... potatoes?

**Additional context:**
I could explain more if you don't understand. It's basically like the different outfits for Hat Kid.

**Comment by Creataurus** [comment]
I second this.

**Comment by Light08** [comment]
Food for thought.
Maybe later when I feel like rewriting the inventory system.

**Comment by Light08** [comment]
On another note, ya know what. Fuck it. Next week.

**Comment by Dispenz0r** [comment]
"next week"

🐐

**Comment by Light08** [comment]
Due to the way the Item Economy System works, stacking isn't exactly possible for any item besides Consumable Items.
Making it work would require a major Item Management Rework which might not be worth the effort, especially due to the upcoming new changes in regards to sorting and managing the Inventory.

I hope the upcoming changes will compensate for this and still fix the initial issue coming from this request, which is the lack of Inventory Management. I'd like to hear some feedback once the Update goes live, and wether "Inventory Stacking" will still be demanded or not. If yes, I'll look into it in the future.

As for sorting the Inventory alphabetically, that might or might not happen for the other item types in the future. It's easier.

**Comment by Light08** [comment]
Feel free to open a new Issue if demand is still there even with the new changes.
