### ISSUE TITLE
Being able to go outside the map in ctf_hl1_bounce

### ISSUE THREAD

**Issue by BimboBumboBambo** [DFS-Servers/BugReportsAndSuggestions#206]
**Steam Profile:** 

- https://steamcommunity.com/id/BimboBumboBambo/
- https://steamcommunity.com/id/59c3aa6e2074c4a96e682e/

**Describe the bug:** The bug/exploit is simple: you are able to go outside the map and shoot through the walls, annoying people and ruining their day in the progress.

**To Reproduce:**

- Only soldiers/demos/wrangler engies can reach the outside of the map. Rocket/sticky jump or sentry rocketjump to reach the edge of the walls and go down.

- Camp

- The wall gives protection. The only real way to get behind there is to do it yourself, which by the time you do will be fested with sentries.

**Expected behavior:** I hope this is fixed. This kind of bug/exploit can rip a match to shreds and ruin the fun for others in the progress apart from those abusing it.

**Server Info:**
> US
> 198.24.171.83:27185

**Additional context:** This map in general might be in my opinion one of the most exploitable and hurrendous maps in TF2. Even instagib was unfun to do here.

![bock](https://user-images.githubusercontent.com/41446589/69188490-ed830d00-0b1c-11ea-8ad8-0cbf04f5c672.png)

**Comment by BimboBumboBambo** [comment]
The reason I added Creataurus in here is that he found the exploit on accident or however you want to call it, hence why I'm making this post.

The screenshot is just one example.
![bock](https://user-images.githubusercontent.com/41446589/69188673-4b175980-0b1d-11ea-80c4-30365accb4bb.png)

Marked red: most suitable for getting behind the map if the RED team isn't attend.
Marked blue: Safest for demo's to stickyjump.
Marked green: The floor itself is buggy as well.

**Comment by Creataurus** [comment]
I also know another spot that's even more exploitable than the spot listed in the picture up there, but I'll send a screenshot when I have the chance to get one.

**Comment by Creataurus** [comment]
I have screenshots of the spot that I found earlier today.
![Exploit Report](https://user-images.githubusercontent.com/42285731/69213504-2325f700-0b19-11ea-9689-d6e2af27e676.jpg)
The red circle is where I sticky jumped to get to the spot in the blue circle. It is also possible to get up there in instagib while the OP Railguns modifier is active, which is how I got to that spot in the first place before sticky jumping.
![20191119215831_1](https://user-images.githubusercontent.com/42285731/69213568-549ec280-0b19-11ea-8d6e-f60a6f0be05d.jpg)
Minus the fact that you can get behind the wall in this screenshot. 
I'd recommend that this map be removed due to how exploitable it can potentially be, even though hardly anyone wants to play on it.

**Comment by BimboBumboBambo** [comment]
That is the exploitable place. It's just another angle.

Aside from that: the map is a total trainwreck. No real way to protect your intel, spawncamping being really easy with BLU's spawn being the biggest victim, jump pads not functioning…

I can go on.

**Comment by Dispenz0r** [comment]
Might replace or remove this map in the near future

**Comment by Dispenz0r** [comment]
Removed the map for now
