### ISSUE TITLE
Rocket jumper deals self percentage damage in smash bros gamemode.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#230]
Tested this out on a couple maps. Done on EU. Player expected behaviour is to take no percentage damage - it doesn't deal percentage damage to other players but it still does damage to the player using it. 

To replicate start up any map with smash bros as the gamemode and try rocket jumping, your percentage will go up. 

![image](https://user-images.githubusercontent.com/52565186/74610855-d12c4780-50ee-11ea-9a4d-9039fbfcf507.png)

**Comment by FortyTwoFortyTwo** [comment]
It may doesn't make sense for jumper weapons to deal damage to yourself, but it actually intended as otherwise there may be possible grief/stall with spam jumping not dealing any damage.

However though, that would make rocket jumper a direct downside weapon (cow mangler exists with infinite ammo over rocket jumper's 60 ammo), so i've blacklisted rocket jumper (and sticky jumper).

**Comment by Dispenz0r** [comment]
Jumper weapons are now blacklisted thanks to 42's update, closing this now.
