### ISSUE TITLE
visible dispenser

### ISSUE THREAD

**Issue by gobaoscar** [DFS-Servers/BugReportsAndSuggestions#260]
**Steam Profile**
https://steamcommunity.com/id/gobaoscar/

**Describe the bug**
then you push the cart on pl maps or then you get the buff in the end of surf_utopia you see a dispenser in the cart or blocking your view

**Expected behavior**
you dont see the dispenser on the cart or blocking your view

**To Reproduce**
go to a pl map or surf map

**Screenshots or error logs**
![20200523214845_1](https://user-images.githubusercontent.com/61912627/82739422-b39af980-9d3f-11ea-9fb6-2b8bf0816c27.jpg)

**Server Info (please complete the following information):**
 EU, 89.35.29.11:27145

**Additional context**
i tested on my side i dont see the dispènser must be in the serverside

**Comment by GreenSwede** [comment]
i believe the most logical explanation to this bug (which we have had for quite a long time now) is that some plugin we got loaded causes this behavior. finding the culprit is going to take a while of testing. i can't think of any potential clues.

@Dispenz0r we may have to do some testing on the USA server someday and try to unload a bunch of plugins until we see the bug disappear.

**Comment by gobaoscar** [comment]
ah then goood luck

**Comment by Dispenz0r** [comment]
Should be fixed with an upcoming update. 

Thanks for the report.
