### ISSUE TITLE
Leaderboards Not Working 

### ISSUE THREAD

**Issue by RealStrade** [DFS-Servers/BugReportsAndSuggestions#29]
All the Servers Leaderboards but 'Total Kills' and 'Items Owned' don't work. It reads : 'There was an error reading from the database. Please try again.'

To Reproduce : /leaderboards, Check Server Leaderboards, then click on anything but 'Total Kills' and 'Items Owned'.

Expected Behaviour : All leaderboards should display the said leaderboards properly.

Server Info : This issue has been reported in all four servers.

![capture d ecran 43](https://user-images.githubusercontent.com/42638723/44697025-4d097e80-aa7a-11e8-96d8-ba41f183f3ce.png)

**Comment by Light08** [comment]
Caused due to a timeout. Sourcemod takes too long to retrieve a result from the database, and just "timeouts". Hard to fix since its kind of a hardcoded thing in SourceMod?
I'm aware of the issue but I'm not sure if I can or will fix it. I'll do some research in the future and see if there's a way to completly fix it but so far I haven't found a solution. Worst case I'll just move the complicated leaderboards over to our Homepage.

**Comment by Dispenz0r** [comment]
This should be completely fixed as of the last major server update
