### ISSUE TITLE
tc_stadium_rc1 causes Crash To Desktop on Linux

### ISSUE THREAD

**Issue by NadeEater** [DFS-Servers/BugReportsAndSuggestions#298]
**Steam Profile**
https://steamcommunity.com/id/grenad/

**Describe the bug**
Loading the tc_stadium_rc1 map causes the game to crash to desktop on Linux (tested on Manjaro, Solus and Ubuntu, no error code given), this bug does not happen with any other map in the rotation.

**Expected behavior**
The game should work normally with no crashes.

**To Reproduce**
Simply loading the map is enough to cause the issue to happen with a 100% "success" rate.

**Screenshots or error logs**
None, the game does not give any upon crashing.

**Server Info (please complete the following information):**
[EU] 89.35.29.11:27145

**Additional context**
None.

**Comment by Dispenz0r** [comment]
The map will not run and will crash if you try to run it on a non-DFS server due to @Light08's DRM protection.

You've mentioned that you were receiving out of memory errors in the DFS discord, I would recommend clearing .cache files, verifying game files and trying again. If that does not work it's likely related to memory issues.
