### ISSUE TITLE
Sandvich can be dropped as friendly

### ISSUE THREAD

**Issue by DarkDragonian** [DFS-Servers/BugReportsAndSuggestions#41]
**Describe the bug**
Heavies in friendly mode can still drop their healthpacks (e. g. Sandvich) to heal others in non-friendly mode.

**Server Info:**
 - Region: UK
 - IP: 89.35.29.11:27145
 - Map: mario_kart_deluxe_v3

**Comment by DarkDragonian** [comment]
Hmmm... then maybe I have a suggestion.
Give all food items an attribute of -100% healing effect while in friendly state.

**Comment by TheRealNexion** [comment]
Wouldn't that kill you though when eating the item then?
It'd have to be 0% healing effect, as -100% healing effect MIGHT mean that instead of healing, it damages you, so eating the sandvich for example, would outright kill you, as it would remove all your health.

And if changing item attribute values doesn't work, maybe remove the throw feature.

**Comment by DarkDragonian** [comment]
![](https://i.imgur.com/77bcjRU.png)
Not really.

But as I've found out, the healing effect does not apply on dropped food.
Perhaps drop something else than a health kit?

**Comment by TheRealNexion** [comment]
Don't know if it's possible to drop something else than a health kit or ammo, but as I said, maybe the throw feature can be removed, or just make the dropped item cosmetic, so when picking it up it just does nothing.
