### ISSUE TITLE
Yet another issue: Evolution stays the same as before

### ISSUE THREAD

**Issue by V1NAlt** [DFS-Servers/BugReportsAndSuggestions#46]
**Describe the bug**
Used a shiny stone, went through the evolution, but my next evolution didn't happen. It said I was a "Regular" but should have been "Leader"

**Expected behavior**
Should immediately evolve to the next evolution.

**Screenshots or error logs**
>_Congratulations! You have evolved into: Leader_
>_Vininator is a Level 102 (812/1295) Regular VIP._ (after the evolution)

**Server Info (please complete the following information):**
 - Region: USA/EU
 - IP 89.35.29.11:27145/198.24.171.83:27185

**Additional context**
The bug does occur in most servers.
Not sure if it's just me or the server that is having this issue.

**Comment by Dispenz0r** [comment]
You probably have to set your title using /profile.

But @Light08 should probably make it so your new rank defaults your current title imo.

**Comment by Light08** [comment]
Type /profile .
It should display your status as Leader. Titles are no longer bound to shiny stones but act as their own thing, which is customizable. As such, your title doesn't "go up" when using a shiny stone unless you specify it.
That ain't a bug but a new feature of the new Title mechanic.

And I won't change it to "update" to your newest status either.

**Comment by Light08** [comment]
Because
A. People might want to stick with their current title, so getting it "updated" would be annoying.
B. It would also reset "custom" titles.

Nothing speaks against the idea of using the options to just change their title to the one they obtained. As for "it's confusing", well, they'll have to deal with it. The Prime Update brought a lot of major changes to already existing elements, so they'll have to get used to the new stuff and how it works.

**Comment by Dispenz0r** [comment]
That makes sense, shame we can't save custom titles for people to use.

How about putting a small notification in the chat whenever someone uses a stone? So they can know that they can use /profile and go options to change their title.

**Comment by Light08** [comment]
Fine.

Done.
