### ISSUE TITLE
/pose Breaking Taunts

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#54]
**Describe the bug:**
Apparently, when you use /pose to do taunts, the taunts that you have in you inventory won't play, even if you forced yourself to stop taunting. It fixes itself if you use a taunt from /taunts though.

**To Reproduce:**
1. Type in /pose
2. Select a speed
3. Taunt using the taunts in your inventory
4. Force yourself out of the taunt

**Expected behaviour:**
The taunts in your inventory should play when you select them.

**Server Info:**
 - Region: Affects all servers.
 - IP: Affects all servers.

**Additional context:**
I don't know if you guys know about this or if it can be fixed just putting this here because why not? ;>

**Comment by Light08** [comment]
Has been a bug for months. Always wondered what's causing it...

**Comment by Afterstormer** [comment]
Any way you can dive in and investigate?

**Comment by Light08** [comment]
Tough one. It used to work before so no idea what broke. Possible that Valve might have broken something with an update (as usual).
We'll see about it but it doesn't have a high priority at the moment.

**Comment by TheRealNexion** [comment]
I don't think this can be fixed, seeing as it probably is Valve's fault, making player taunts conflict with the /taunt and /pose plugins...
Another thing I noticed is, that the taunts you own might not play because the speed from /pose makes the taunt glitch out, as in: Using any slower than normal speed, using an owned taunt, and then stopping the taunt.
When this happens, you will not be able to taunt again after the original taunt you made stops by itself at the speed you set it before manually stopping it, like it's still running in the background at that speed.

**Comment by Dispenz0r** [comment]
Nothing we can do about it really.
