### ISSUE TITLE
Freerun button breaks dr_firetemple's locked doors

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#6]
Like the title says, if the death hits the freerun button, the locks on the doors won't break, even if you collect the specific key for them. It doesn't affect all doors though, but the boss lock doesn't break on a freerun.

**Comment by Bert54** [comment]
Upon activating Freerun, the super key spawns, which can unlock all regular locked door on top of the regular keys opening their respective door.
That issue is really weird, because this never occured in any other deathrun server. 
Please make sure a plugin isn't interfering with the map I/O system in any ways.

**Comment by Dispenz0r** [comment]
We've always used Deathrun Redux (https://forums.alliedmods.net/showthread.php?p=2224003) to run our DR maps, we never ran into this kind of an issue before with any other map.

I assume it's related to the map somehow? I'm not sure, in the worst case scenario we could replace the map with something else.

**Comment by Bert54** [comment]
And it is the exact same plugin that's used in the servers I'm talking about.

Regardless, feel free to replace dr_firetemple with another map, as I will not update the map with this "issue" fixed as long as I don't have a solid proof about the same issue being replicated into another server outside of DFS. This system has been up since the b2 version, the key system has never been modified ever since (yet) and this never occured before, either in this version or in a previous one.

The only thing I can promise however is to look into it if a footage of the issue happening in real time is provided to me.

**Comment by Light08** [comment]
Maybe Stripper might be causing conflicts?

Where exactly does the  "Super Key" spawn and is there anything special regarding its spawn?
I assume you're using a point_template to spawn it...

**Comment by Bert54** [comment]
Nothing special about it, just a func_brush, an env_sprite and a trigger_once altogether enabled when the freerun button is hit.

No, I am not using a point_template for this one. I usually use that point entity only when I have multiple similar objects to spawn.

**Comment by Afterstormer** [comment]
Alright, so this may be a false alarm.
In all the freeruns that have been issued to us, it seems that all the doors work as they should, so I don't think any action needs to be taken.
Sorry for the misunderstanding.
