### ISSUE TITLE
Auction not ending after going over deadline

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#66]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

The bug is that my auction has not ended but it has passed it's deadline

**To Reproduce**
1. put an item on the auctionhouse
2. have someone place an offer on it
3. wait
4. credits nor items have not been recieved

**Expected behavior*
The items and credits being sent

**Screenshots or error logs**
https://steamcommunity.com/sharedfiles/filedetails/?id=1531153254

**Server Info (please complete the following information):**
 - Region: [EU]
 - IP [89.35.29.11:27145]

**Comment by Light08** [comment]
AuctionHouse has undergone a major overhaul with tons of QoL changes, new additions and bug fixes.
That means, this bug here is also going to be fixed, most likely even before the actual update goes live in the coming time!

Better start making offers on all these items you have an eye on, because the Deadline will have most of the auctions ended. Right now I'm doing some final tests on the new system, once I'm sure it completly works, it will go live on DFS asap. Possibly already this week.
