### ISSUE TITLE
Disable falldamage option not working in the /gold option menu

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#78]
**Steam Profile*
https://steamcommunity.com/id/vilxxu/
**Describe the bug**
The bug is that the disable falldamage option is not working at all even in friendly maps

**To Reproduce**
1. do /gold
2. Disable falldamage thru the options
3. Take some falldamage or just a falldamage killzone

**Expected behavior**
Falldamage not being taken

**Server Info**
 - Region: [EU]
 - IP [89.35.29.11:27145]

**Additional context**
I encountered the bug on arena_metal_gear_solid_1

**Comment by Light08** [comment]
That's its new behavior that has been there for some time.
It does **not** ignore Triggers that cast Fall damage, hence why the metal_gear map still damages people.

Original intention was to avoid abuse on certain gamemodes (like Deathrun), but since I've also disabled the use on gamemode maps, I might consider reverting the mechanic.
Unless Fall damage neglation doesn't work at all (falling from a height), I'll close this one for now.
