### ISSUE TITLE
Super Zombie Fortress (BLUs respawn too quickly)

### ISSUE THREAD

**Issue by ntpplcbl** [DFS-Servers/BugReportsAndSuggestions#84]
Hi-diddly-ho!
**Problem**:
  Yes so currently BLUs respawn instantly. But dude it's like gives them a huge advantage over REDs.
**Suggestion**:
Please make it so BLUs have a respawn time (10 seconds should be optimal I think).

 Thanks for reading. xoxo, Ninja Assassin

**Comment by ramunecarbonated** [comment]
does this happen for the whole round, from the start until the end?

**Comment by ntpplcbl** [comment]
Yes this happens the whole round.

**Comment by ramunecarbonated** [comment]
It uses tf2 map logic to influence the respawn times (which is basic stuff every tf2 map has/shluld have), so unless there is concrete proof of the Infected having the fast respawn stuff from a frenzy I am closing this due to this not being reported to me from any other channel of source but this post, thanks anyway and if you have screenshots/footage of this then do send them.

**Comment by Dispenz0r** [comment]
I think I know why this happens, gonna try to fix it on the next server maintenance

**Comment by ramunecarbonated** [comment]
>closes requesting for more proof
>reopens without said proof
why?

**Comment by Dispenz0r** [comment]
> > closes requesting for more proof
> > reopens without said proof
> 
> huh?

I re-opened it for a good reason, respawn times are disabled in DFS.

I'll just have to enable them on SZF on next maintenance, don't close this thanks

**Comment by Benoist3012** [comment]
it's close & open war!

**Comment by Dispenz0r** [comment]
Should be hopefully fixed now, thanks for reporting!

Gave a Community Box as well, please let us know if the issue persists!
